hugoblox:
  schema: "2.0"
  identity:
    name: Daniel Ramirez
    type: person
    tagline: Data Science Freelancer | Marketing Analytics Specialist
    description: ""
    organization: Freelancer
  theme:
    mode: dark
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: "stone"
    colors_light:
      neutral: ""
      secondary: ""
      primary: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    theme_picker: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
    citations:
      style: mla
  search:
    enable: true
